name: User API Build

on: workflow_dispatch

env:
  working-directory: ./users-api

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/workflows/maven.yaml
        with:
          version: '8'
          working-directory: ./users-api

  Docker:
    uses: ./.github/workflows/docker-image-build.yaml
    with:
      image-name: ms-java
      version: 0.0.1
      working-directory: ./users-api
    needs: Build
    secrets: inherit