name: User API Build

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./users-api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'

      - name: Maven Install
        working-directory: ${{env.working-directory}}
        run: ./mvnw clean install

      - name: Build Docker Image
        working-directory: ${{env.working-directory}}
        run: docker build . -t userapi:0.0.1
