name: User API Build

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      language-version:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  maven-build:
    if: ${{inputs.language == 'java'}}
    uses: ./.github/workflows/maven.yaml
    with:
      version: ${{inputs.language-version}}
      working-directory: ${{inputs.working-directory}}

  nodejs-build:
    if: ${{inputs.language == 'nodejs'}}
    uses: ./.github/workflows/nodejs.yaml
    with:
      version: ${{inputs.language-version}}
      working-directory: ${{inputs.working-directory}}

  docker-push:
    uses: ./.github/workflows/docker-image-build.yaml
    with:
      image-name: ${{inputs.image-name}}
      version: ${{inputs.image-version}}
      working-directory: ${{inputs.working-directory}}
    needs: [maven-build, nodejs-build]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    secrets: inherit