name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  Docker:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t ${{inputs.image-name}}:${{inputs.version}}