name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string
      working-directory:
        required: true
        type: string

env:
  ecr-base-url: 479699168399.dkr.ecr.ap-southeast-1.amazonaws.com

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build . -t ${{env.ecr-base-url}}/${{inputs.image-name}}:${{inputs.version}}
          docker push ${{env.ecr-base-url}}/${{inputs.image-name}}:${{inputs.version}}
        working-directory: ${{inputs.working-directory}}