name: Maven Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: ${{inputs.version}}
          distribution: 'corretto'
          cache: 'maven'

      - name: Build Project
        working-directory: ${{inputs.working-directory}}
        run: ./mvnw clean install -DskipTests

      - name: Run Unit Tests
        working-directory: ${{inputs.working-directory}}
        run: ./mvnw test