name: Java MS Build

on: workflow_dispatch

jobs:
  uses: ./.github/workflows/build.yaml
  with:
    language: 'java'
    language-version: '8'
    image-name: 'ms-java'
    image-version: '0.0.1'
    working-directory: './user-service'
  secrets: inherit