name: NodeJs Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.version}}
          cache: 'npm'
          node-version-file: '${{inputs.working-directory}}/package.json'
          cache-dependency-path: '${{inputs.working-directory}}/package-lock.json'

      - name: Build Project
        working-directory: ${{inputs.working-directory}}
        run: npm ci

      - name: Run Unit Tests
        working-directory: ${{inputs.working-directory}}
        run: npm test