name: User Service Build

on: workflow_dispatch

env:
  working-directory: ./users-service

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'npm'
          node-version-file: '${{env.working-directory}}/package.json'
          cache-dependency-path: '${{env.working-directory}}/package-lock.json'

      - name: Build Project
        working-directory: ${{env.working-directory}}
        run: npm install

      - name: Run Unit Tests
        working-directory: ${{env.working-directory}}
        run: npm test

  Docker:
    uses: ./.github/workflows/docker-image-build.yaml
    with:
      image-name: usersservice
      version: 0.0.1
      working-directory: ./users-service
    needs: Build